name: build

on:
  push:
    branches: [ master ]
    tags:
      - v*
      - p*
  pull_request:
    branches: [ master ]

  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  build:
    name: ${{ matrix.python }} ${{ matrix.os }} ${{ matrix.plat }} ${{ matrix.parallel }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-24.04, macos-15 ]
        python: [ '3.8', '3.9', '3.10', '3.11', '3.12', '3.13' ]
        manylinux: [ 2014 ]
        plat: [ x86_64, arm64 ]
        parallel: [ serial ]
        exclude:
          - os: ubuntu-24.04
            plat: arm64
          - os: macos-15
            plat: x86_64
      fail-fast: false

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python }}

      - name: setup macOS build tools
        if: matrix.os == 'macos-15'
        run: |
          brew update
          brew install libomp
          brew install gnu-sed

      - name: install requirements (linux)
        if: matrix.os == 'ubuntu-24.04'
        env:
          MKLROOT: ~/.local
        run: |
          python -m pip install pip build twine setuptools pytest --upgrade
          python -m pip install mkl==2021.4 mkl-include intel-openmp numpy psutil 'cmake>=3.19' pybind11==2.12.0

      - name: install requirements (macOS)
        if: matrix.os == 'macos-15'
        run: |
          python -m pip install pip build twine setuptools pytest --upgrade
          python -m pip install numpy psutil 'cmake>=3.19' pybind11==2.12.0

      - name: install requirements (linux / mpi)
        if: matrix.os == 'ubuntu-24.04'
        run: |
          sudo apt-get install libopenmpi-dev
          python -m pip install mpi4py

      - name: fix mkl for amd cpu
        if: matrix.os == 'ubuntu-24.04'
        run: |
          lscpu
          export CPUTYPE=$(lscpu | grep 'Vendor ID' | awk '{print $3}')
          echo $CPUTYPE
          if [ "$CPUTYPE" = "AuthenticAMD" ]; then
            echo "int mkl_serv_intel_cpu_true() { return 1; }" > fixcpu.c
            gcc -shared -fPIC -o libfixcpu.so fixcpu.c
          fi
          getconf LONG_BIT

      - name: build test (linux)
        if: matrix.os == 'ubuntu-24.04'
        env:
          MKLROOT: ~/.local
        run: |
          mkdir build
          cd build
          cmake .. -DUSE_MKL=ON
          make -j 4
          cd ..
          echo "PYTHONPATH=./build:${PYTHONPATH}" >> $GITHUB_ENV

      - name: build test (macOS arm64)
        if: matrix.os == 'macos-15'
        env:
          MACOSX_DEPLOYMENT_TARGET: '11.0'
        run: |
          export OMPROOT=$(brew --prefix libomp)
          mkdir build
          cd build
          cmake .. -DUSE_MKL=OFF -DARCH_ARM64=ON -DOMP_LIB=OMP -DCMAKE_CXX_FLAGS=-I${OMPROOT}/include
          make -j 4
          cd ..
          echo "PYTHONPATH=./build:${PYTHONPATH}" >> $GITHUB_ENV

      - name: run test (serial, linux)
        if: matrix.os == 'ubuntu-24.04'
        env:
          MKLROOT: ~/.local
        run: |
          export CPUTYPE=$(lscpu | grep 'Vendor ID' | awk '{print $3}')
          if [ "$CPUTYPE" = "AuthenticAMD" ]; then
            export LD_PRELOAD=$PWD/libfixcpu.so
          fi
          python -m pytest pyblock3/algebra
          python -m pytest pyblock3/algorithms --ignore=pyblock3/algorithms/tests/test_soc.py

      - name: run test (serial, macOS)
        if: matrix.os == 'macos-15'
        run: |
          python -m pytest pyblock3/algebra
          python -m pytest pyblock3/algorithms --ignore=pyblock3/algorithms/tests/test_soc.py

      - name: build wheels (macos-arm64)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'macos-15' && matrix.plat == 'arm64'
        env:
          TAG_STRING: ${{ github.event.ref }}
          MACOSX_DEPLOYMENT_TARGET: '11.0'
          HOMEBREW_NO_INSTALLED_DEPENDENTS_CHECK: 1
        run: |
          export PATH=/opt/homebrew/opt/gnu-sed/libexec/gnubin:$PATH
          echo ${TAG_STRING:11}
          export OMPROOT=$(brew --prefix libomp)
          gsed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          gsed -i "/DUSE_MKL/a \                '-DOMP_LIB=OMP'," setup.py
          gsed -i "/DUSE_MKL/a \                '-DARCH_ARM64=ON'," setup.py
          gsed -i "/mkl/d" setup.py
          gsed -i "/intel-openmp/d" setup.py
          gsed -i "/DUSE_MKL/c \                '-DUSE_MKL=OFF'," setup.py
          cmake --version
          python -m pip install wheel delocate==0.10.7
          export _PYTHON_HOST_PLATFORM="macosx-15.0-arm64"
          export SDKROOT=$(xcrun --sdk macosx --show-sdk-path)
          export PLAT="arm64"
          python -m pip wheel . -w ./dist --no-deps
          delocate-wheel --require-archs=arm64 -k dist/*.whl

      - name: prepare build wheels (manylinux)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-24.04'
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          cp ./.github/actions/build-wheel/Dockerfile.manylinux${{ matrix.manylinux }} ./.github/actions/build-wheel/Dockerfile

      - name: build wheels (manylinux)
        if: startsWith(github.ref, 'refs/tags/') && matrix.os == 'ubuntu-24.04'
        uses: ./.github/actions/build-wheel
        with:
          python-version: ${{ matrix.python }}
          parallel: ${{ matrix.parallel }}

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: actions/upload-artifact@v4
        with:
          name: dist-${{ matrix.parallel }}-${{ matrix.python }}-${{ matrix.os }}-${{ matrix.plat }}
          path: dist
          retention-days: 2

  pypi:
    name: pypi
    needs: [build]
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/')
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: build source dist (serial)
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          python -m pip install pip build twine setuptools --upgrade
          python -m build --sdist

      - name: release
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*

      - name: build index
        env:
          REPO: ${{ github.repository }}
        run: |
          python .github/workflows/build_pypi.py ${REPO} ./idx-dist/pypi

      - name: setup pages
        uses: actions/configure-pages@v5

      - name: upload artifacts
        uses: actions/upload-pages-artifact@v3
        with:
          path: './idx-dist'

      - name: deploy to gitHub pages
        id: deployment
        uses: actions/deploy-pages@v4

  publish:
    name: publish
    needs: build
    runs-on: ubuntu-24.04
    if: startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: build source dist (serial)
        env:
          TAG_STRING: ${{ github.event.ref }}
        run: |
          echo ${TAG_STRING:11}
          sed -i "s/version=.*/version='${TAG_STRING:11}',/" setup.py
          python -m pip install pip build twine setuptools --upgrade
          python -m build --sdist

      - name: download wheels
        uses: actions/download-artifact@v4
        with:
          pattern: dist-serial-*
          path: dist
          merge-multiple: true

      - name: publish to pypi
        uses: pypa/gh-action-pypi-publish@release/v1
